# Generated by Django 5.2.7 on 2026-01-25 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0001_initial'),
        ('nano', '0017_airtimeproduct_airtimerequest_airtimesale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrderingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('restaurant_view', 'Restaurant View'), ('menu_browse', 'Menu Browse'), ('item_view', 'Menu Item View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout', 'Checkout'), ('payment', 'Payment'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('delivery_tracking', 'Delivery Tracking'), ('review_left', 'Review Left'), ('search_restaurant', 'Search Restaurant'), ('filter_menu', 'Filter Menu'), ('barcode_scan', 'Barcode Scan')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional activity data')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Activity duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nano.deviceconnection')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='food_ordering.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='food_ordering.order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='food_ordering.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'created_at'], name='food_orderi_user_id_26592d_idx'), models.Index(fields=['activity_type', 'created_at'], name='food_orderi_activit_d4e0be_idx'), models.Index(fields=['restaurant', 'created_at'], name='food_orderi_restaur_73e7a2_idx'), models.Index(fields=['order', 'created_at'], name='food_orderi_order_i_6f24ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderingDeviceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurants_viewed', models.PositiveIntegerField(default=0)),
                ('menu_items_viewed', models.PositiveIntegerField(default=0)),
                ('orders_placed', models.PositiveIntegerField(default=0)),
                ('cart_additions', models.PositiveIntegerField(default=0)),
                ('checkout_attempts', models.PositiveIntegerField(default=0)),
                ('payments_completed', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('actions_performed', models.PositiveIntegerField(default=0)),
                ('data_transferred_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='food_orderi_user_id_93d9e7_idx'), models.Index(fields=['device_id'], name='food_orderi_device__5f914e_idx'), models.Index(fields=['session_start'], name='food_orderi_session_53ab95_idx'), models.Index(fields=['last_activity'], name='food_orderi_last_ac_6ebb68_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('order_error', 'Order Error'), ('payment_error', 'Payment Error'), ('inventory_error', 'Inventory Error'), ('delivery_error', 'Delivery Error'), ('menu_error', 'Menu Error'), ('restaurant_error', 'Restaurant Error'), ('customer_error', 'Customer Error'), ('integration_error', 'Integration Error'), ('validation_error', 'Validation Error'), ('api_error', 'API Error')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('user_action', models.CharField(blank=True, help_text='What the user was trying to do', max_length=100)),
                ('form_data', models.JSONField(blank=True, help_text='Form data that caused the error', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nano.deviceconnection')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='food_ordering.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='food_ordering.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_food_errors', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='food_ordering.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['error_type', 'severity'], name='food_orderi_error_t_cdaec8_idx'), models.Index(fields=['user', 'created_at'], name='food_orderi_user_id_dd7f2d_idx'), models.Index(fields=['restaurant', 'created_at'], name='food_orderi_restaur_865f17_idx'), models.Index(fields=['is_resolved'], name='food_orderi_is_reso_1a83cd_idx'), models.Index(fields=['created_at'], name='food_orderi_created_5425cf_idx')],
            },
        ),
    ]
