# Generated by Django 5.2.7 on 2025-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('snacks_chips', 'Snacks & Chips'), ('cold_drinks', 'Cold Drinks'), ('sweets_treats', 'Sweets & Treats'), ('basic_groceries', 'Basic Groceries'), ('dairy_eggs', 'Dairy & Eggs'), ('bread_baked', 'Bread & Baked Goods'), ('canned_goods', 'Canned Goods'), ('personal_care', 'Personal Care'), ('household_items', 'Household Items'), ('airtime_data', 'Airtime & Data'), ('frozen_goods', 'Frozen Goods'), ('tuckshop_packs', 'Tuckshop Packs'), ('stationery', 'Stationery'), ('baby_products', 'Baby Products'), ('seasonal_items', 'Seasonal Items')], default='basic_groceries', max_length=20),
        ),
    ]
