# Generated by Django 5.2.7 on 2025-10-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0006_completedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
