# Generated by Django 4.2.7 on 2025-10-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start_date',
            field=models.DateTimeField(default=None, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end_date',
            field=models.DateTimeField(default=None, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
