# Generated by Django 5.2.7 on 2025-10-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0009_product_sale_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
