# Generated by Django 5.2.7 on 2025-10-20 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0010_product_barcode_alter_product_sale_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lowest_warehouse', models.CharField(max_length=100)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compared_warehouses', models.JSONField(default=list)),
                ('all_prices', models.JSONField(default=dict)),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-comparison_date'],
                'indexes': [models.Index(fields=['product_name'], name='nano_pricec_product_3632b4_idx'), models.Index(fields=['barcode'], name='nano_pricec_barcode_c21dd8_idx'), models.Index(fields=['lowest_price'], name='nano_pricec_lowest__3082b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarehousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('warehouse_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('unit_size', models.CharField(blank=True, max_length=50, null=True)),
                ('date_imported', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_imported'],
                'indexes': [models.Index(fields=['product_name', 'warehouse_name'], name='nano_wareho_product_18aa92_idx'), models.Index(fields=['barcode'], name='nano_wareho_barcode_205de2_idx')],
            },
        ),
    ]
