# Generated by Django 5.2.7 on 2025-12-01 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0015_add_fcm_token_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('actions_performed', models.PositiveIntegerField(default=0)),
                ('data_transferred_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('user_error', 'User Error'), ('system_error', 'System Error'), ('validation_error', 'Validation Error'), ('permission_error', 'Permission Error'), ('api_error', 'API Error'), ('database_error', 'Database Error'), ('network_error', 'Network Error'), ('payment_error', 'Payment Error')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('user_action', models.CharField(blank=True, help_text='What the user was trying to do', max_length=100)),
                ('form_data', models.JSONField(blank=True, help_text='Form data that caused the error', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nano.deviceconnection')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout', 'Checkout'), ('payment', 'Payment'), ('search', 'Search'), ('filter', 'Filter'), ('sort', 'Sort'), ('error', 'Error'), ('form_submit', 'Form Submit'), ('api_call', 'API Call')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('object_type', models.CharField(blank=True, help_text='Type of object acted upon', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of object acted upon', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional activity data')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Activity duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nano.deviceconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceconnection',
            index=models.Index(fields=['user', 'is_active'], name='nano_device_user_id_1bb0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceconnection',
            index=models.Index(fields=['device_id'], name='nano_device_device__4b9de5_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceconnection',
            index=models.Index(fields=['session_start'], name='nano_device_session_284cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceconnection',
            index=models.Index(fields=['last_activity'], name='nano_device_last_ac_0cccd4_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_type', 'severity'], name='nano_errorl_error_t_211f57_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', 'created_at'], name='nano_errorl_user_id_8d2cff_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['is_resolved'], name='nano_errorl_is_reso_ae5630_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['created_at'], name='nano_errorl_created_786025_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', 'created_at'], name='nano_userac_user_id_8a2285_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', 'created_at'], name='nano_userac_activit_85f2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='nano_userac_created_5f2929_idx'),
        ),
    ]
