# Generated by Django 5.2.7 on 2025-12-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0016_deviceconnection_errorlog_useractivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('vodacom', 'Vodacom'), ('mtn', 'MTN'), ('telkom', 'Telkom'), ('cell_c', 'Cell C'), ('rain', 'Rain'), ('blu', 'BLU')], max_length=10)),
                ('airtime_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('sms_bundle', 'SMS Bundle'), ('combo', 'Combo')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Value in Rands', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirtimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('add_airtime', 'Add Airtime Product'), ('update_stock', 'Update Airtime Stock'), ('bulk_airtime', 'Bulk Airtime Operation')], max_length=20)),
                ('target_role', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='manager', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('request_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_airtime_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_management_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirtimeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airtime_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nano.airtimeproduct')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_airtime', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
