# Generated by Django 5.2.7 on 2026-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0018_adminactionlog_apicalllog_datamodificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodificationlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datamodificationlog',
            name='request_method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datamodificationlog',
            name='request_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='datamodificationlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
