# Generated by Django 5.2.7 on 2026-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0019_alter_datamodificationlog_object_repr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='completedorder',
            name='customer_email_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedorder',
            name='customer_name_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedorder',
            name='customer_phone_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
