# Generated by Django 5.2.7 on 2026-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0020_add_customer_encryption_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for display purposes', max_length=100, null=True),
        ),
    ]
