# Generated by Django 4.2.25 on 2026-05-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0021_userprofile_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='airtimeproduct',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_products', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='airtimerequest',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_requests', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='airtimesale',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_sales', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='completedorder',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_orders', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='datamodificationlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_modification_logs', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='deviceconnection',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_connections', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='pricecomparison',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_comparisons', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='product',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='sale',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_audit_logs', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='sensitivedataaccesslog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_data_access_logs', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='nano.workspace'),
        ),
        migrations.AddField(
            model_name='warehouseprice',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_prices', to='nano.workspace'),
        ),
    ]
