# Generated by Django 5.2.17 on 2026-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0024_pendingorder_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicalllog',
            name='endpoint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datamodificationlog',
            name='request_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sensitivedataaccesslog',
            name='request_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='page_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
