"""
Django settings for confige project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS configuration
if DEBUG:
    # Also add for mobile using ipconfig
    ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1,172.20.48.1,10.39.110.47').split(',')
else:
    # Production - Explicitly allow the specific Render.com domain
    ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='ndtechpos.onrender.com,.onrender.com').split(',')
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'nano','food_ordering','NDtechTrack',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Enhanced security middleware (order is important)
    'nano.enhanced_security_middleware.PrivacyComplianceMiddleware',
    'nano.enhanced_security_middleware.EnhancedSecurityMiddleware',
    'nano.enhanced_security_middleware.SensitiveDataMaskingMiddleware',
    'nano.enhanced_security_middleware.DataRetentionMiddleware',
    # Original audit logging middleware
    'nano.middleware.ThreadLocalMiddleware',
    'nano.middleware.SecurityAuditMiddleware',
    'nano.middleware.DataModificationMiddleware',
]

ROOT_URLCONF = 'confige.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'confige.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - SQLite only (force SQLite even in production)
import os

# Ignore any DATABASE_URL environment variable to ensure SQLite is always used
if 'DATABASE_URL' in os.environ:
    del os.environ['DATABASE_URL']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom authentication backend
AUTHENTICATION_BACKENDS = [
    'nano.authentication.UserProfileBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static files directory for PWA
STATICFILES_DIRS = [
    BASE_DIR / 'nano' / 'static',
]

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = '/sign_in/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/register/'

# Trust proxy headers from nginx
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000').split(',')

# CSRF Trusted Origins - Handle both local and production environments
if DEBUG:
    CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8080,http://127.0.0.1:8080,http://localhost:8000,http://127.0.0.1:8000').split(',')
else:
    # Production - Add your Render.com URL here
    render_url = config('RENDER_URL', default='https://ndtechpos.onrender.com').strip()
    trusted_origins = ['https://ndtechpos.onrender.com']
    if render_url and render_url not in trusted_origins:
        trusted_origins.append(render_url)
    CSRF_TRUSTED_ORIGINS = trusted_origins

# PWA Service Worker Settings
PWA_SERVICE_WORKER_PATH = 'static/nano/sw.js'
PWA_APP_MANIFEST_PATH = 'static/nano/manifest.json'

# Firebase Cloud Messaging (FCM) Settings
FCM_API_KEY = config('FCM_API_KEY')
FCM_SENDER_ID = config('FCM_SENDER_ID', default='')
FCM_PROJECT_ID = config('FCM_PROJECT_ID', default='')

# Brevo Email Service Settings
BREVO_API_KEY = config('BREVO_API_KEY')
BREVO_SENDER_EMAIL = config('BREVO_SENDER_EMAIL')
BREVO_SENDER_NAME = config('BREVO_SENDER_NAME')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'audit': {
            'format': '{asctime} {levelname} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': config('LOG_LEVEL', default='INFO'),
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'fcm_notifications.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security_audit.log',
            'formatter': 'audit',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security_events.log',
            'formatter': 'audit',
        },
    },
    'loggers': {
        'nano.fcm_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': config('LOG_LEVEL', default='INFO'),
        },
        'security_audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'nano.middleware': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Audit Logging Settings
AUDIT_LOGGING = {
    'ENABLE_SECURITY_LOGGING': True,
    'ENABLE_DATA_MODIFICATION_LOGGING': True,
    'ENABLE_API_LOGGING': True,
    'ENABLE_SENSITIVE_DATA_LOGGING': True,
    'LOG_ANONYMOUS_REQUESTS': False,
    'MAX_REQUEST_BODY_SIZE': 10000,  # Maximum request body size to log (bytes)
    'MAX_RESPONSE_BODY_SIZE': 500,   # Maximum response body size to log (bytes)
    'EXCLUDE_URLS': [
        '/static/',
        '/media/',
        '/favicon.ico',
        '/robots.txt',
        '/admin/jsi18n/',
        '/__debug__/',
    ],
    'EXCLUDE_HTTP_METHODS': ['OPTIONS', 'HEAD'],
    'SENSITIVE_DATA_FIELDS': [
        'password', 'token', 'secret', 'key', 'csrfmiddlewaretoken',
        'credit_card', 'ssn', 'social_security', 'bank_account'
    ],
}

# Rate Limiting Settings (for future implementation)
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_CACHE = 'default'

# Session Security Settings
SESSION_COOKIE_AGE = 3600 * 8  # 8 hours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
if not DEBUG:
    SESSION_COOKIE_SECURE = True

# CSRF Security Settings
CSRF_COOKIE_AGE = 3600 * 24  # 24 hours
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
if not DEBUG:
    CSRF_COOKIE_SECURE = True

# Additional Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'NDtech POS API',
    'DESCRIPTION': 'Complete Point of Sale system API with comprehensive audit logging, security tracking, and business analytics',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development server'},
        {'url': 'https://ndtechpos.onrender.com', 'description': 'Production server'},
    ],
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and authorization'},
        {'name': 'Products', 'description': 'Product management and inventory'},
        {'name': 'Sales', 'description': 'Sales order management'},
        {'name': 'Notifications', 'description': 'User notifications and alerts'},
        {'name': 'Security', 'description': 'Security events and audit logs'},
        {'name': 'Airtime', 'description': 'Airtime product management'},
        {'name': 'Warehouse', 'description': 'Warehouse price comparisons'},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': True,
        'hideHostname': True,
    },
    # 'PREPROCESSING_HOOKS': [
    #     'nano.api_hooks.remove_csrf_from_docs',
    # ],
}

# Enhanced Data Protection Settings
DATA_PROTECTION = {
    'ENABLE_DATA_ENCRYPTION': False,  # Set to True when implementing field encryption
    'ENABLE_DATA_ANONYMIZATION': True,
    'ENABLE_AUTOMATIC_CLEANUP': True,
    'MASK_SENSITIVE_DATA_IN_LOGS': True,
    'MASK_SENSITIVE_DATA_IN_RESPONSES': True,
}

# Data Retention Policies (in days)
DATA_RETENTION_DAYS = {
    'security_logs': 365,      # 1 year
    'audit_logs': 2555,        # 7 years (legal requirement)
    'api_logs': 90,            # 3 months
    'user_activity': 365,       # 1 year
    'error_logs': 180,         # 6 months
    'sensitive_data_access': 365, # 1 year
    'temp_files': 7,           # 1 week
}

# Privacy and GDPR Settings
PRIVACY_SETTINGS = {
    'ENABLE_GDPR_COMPLIANCE': True,
    'ENABLE_CONSENT_MANAGEMENT': True,
    'ENABLE_DATA_SUBJECT_REQUESTS': True,
    'ENABLE_PRIVACY_DASHBOARD': True,
    'COOKIE_CONSENT_REQUIRED': True,
    'DATA_PROCESSING_PURPOSES': [
        'essential',      # Essential for service operation
        'analytics',      # Analytics and improvement
        'marketing',      # Marketing communications
        'personalization', # Personalization
        'security',       # Security and fraud prevention
    ],
}

# Enhanced Security Logging
ENHANCED_SECURITY_LOGGING = {
    'ENABLE_SENSITIVE_PATTERN_DETECTION': True,
    'ENABLE_DATA_LEAKAGE_DETECTION': True,
    'ENABLE_AUTOMATED_THREAT_RESPONSE': True,
    'LOG_MASKED_DATA': True,
    'DETECT_PATTERNS': [
        r'password["\s]*[:=]["\s]*[^"\\s]+',
        r'token["\s]*[:=]["\s]*[^"\\s]+',
        r'secret["\s]*[:=]["\s]*[^"\\s]+',
        r'key["\s]*[:=]["\s]*[^"\\s]+',
        r'\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b',  # Credit card
        r'\b\d{3}[-\s]?\d{2}[-\s]?\d{4}\b',  # SSN
    ],
}

# Security Headers Configuration
SECURITY_HEADERS = {
    'ENABLE_CSP': True,
    'ENABLE_HSTS': True,
    'ENABLE_XSS_PROTECTION': True,
    'ENABLE_FRAME_PROTECTION': True,
    'ENABLE_CONTENT_TYPE_OPTIONS': True,
    'CUSTOM_HEADERS': {
        'X-Privacy-Policy': 'https://ndtechpos.com/privacy',
        'X-GDPR-Compliant': 'true',
        'X-Data-Protection': 'enabled',
    },
}
