# Generated by Django 5.2.7 on 2026-01-29 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical System Issue'), ('high', 'High Priority Issue'), ('medium', 'Medium Priority Issue'), ('low', 'Low Priority Issue'), ('info', 'Informational')], max_length=20)),
                ('affected_url', models.URLField()),
                ('error_details', models.JSONField(default=dict)),
                ('stack_trace', models.TextField(blank=True)),
                ('detection_method', models.CharField(max_length=50)),
                ('detection_data', models.JSONField(default=dict)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolution_method', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_channels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_type', 'severity', 'created_at'], name='NDtechTrack_issue_t_0f455d_idx'), models.Index(fields=['auto_resolved', 'resolved_at'], name='NDtechTrack_auto_re_a75569_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_count', models.IntegerField()),
                ('unique_users_affected', models.IntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('trend_direction', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable'), ('spike', 'Spike')], max_length=20)),
                ('predicted_next_period', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['error_type', 'period_start'], name='NDtechTrack_error_t_b69175_idx'), models.Index(fields=['period_type', 'period_start'], name='NDtechTrack_period__d00fee_idx'), models.Index(fields=['trend_direction', 'period_start'], name='NDtechTrack_trend_d_98fe1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('error_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_activity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('system_resource_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent (>90)'), ('good', 'Good (75-90)'), ('fair', 'Fair (60-75)'), ('poor', 'Poor (<60)')], max_length=20)),
                ('recommendations', models.JSONField(default=list)),
                ('critical_issues', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['health_status', 'calculated_at'], name='NDtechTrack_health__72de10_idx'), models.Index(fields=['score', 'calculated_at'], name='NDtechTrack_score_09278b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(default='count', max_length=20)),
                ('status', models.CharField(choices=[('optimal', 'Optimal'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['metric_name', 'status'], name='NDtechTrack_metric__5cb6cd_idx'), models.Index(fields=['status', 'measured_at'], name='NDtechTrack_status_1e83df_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical', 'Critical System Issue'), ('high', 'High Priority Issue'), ('medium', 'Medium Priority Issue'), ('low', 'Low Priority Issue'), ('info', 'Informational')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical System Issue'), ('high', 'High Priority Issue'), ('medium', 'Medium Priority Issue'), ('low', 'Low Priority Issue'), ('info', 'Informational')], max_length=20)),
                ('affected_systems', models.JSONField(default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_escalate', models.BooleanField(default=False)),
                ('escalation_threshold_minutes', models.IntegerField(default=30)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('affected_users', models.ManyToManyField(blank=True, related_name='affected_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity', 'created_at'], name='NDtechTrack_alert_t_82bc0e_idx'), models.Index(fields=['is_active', 'resolved_at'], name='NDtechTrack_is_acti_47e720_idx'), models.Index(fields=['auto_escalate', 'escalated_at'], name='NDtechTrack_auto_es_aa5576_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=50)),
                ('pattern_description', models.TextField()),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_seen'],
                'indexes': [models.Index(fields=['user', 'error_type'], name='NDtechTrack_user_id_b33215_idx'), models.Index(fields=['occurrence_count', 'is_active'], name='NDtechTrack_occurre_e11fb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('page_views', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('actions_completed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ended_naturally', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='NDtechTrack_user_id_d841c9_idx'), models.Index(fields=['is_active', 'end_time'], name='NDtechTrack_is_acti_6cdac2_idx'), models.Index(fields=['device_type', 'start_time'], name='NDtechTrack_device__e1cbb7_idx')],
            },
        ),
    ]
